## python 을 이용한 database

conda install pymysql  입력

In [4]:
import pymysql

conn = None #전역변수로 conn 변수 생성함. 

try:
    conn = pymysql.connect(
        host ='localhost', user='root', password=비밀번호,
        db='python', charset='utf8') #데이터베이스 접속

    with conn.cursor() as cursor: #Cursor 객체 생성

        sql = '''CREATE TABLE mysql (
                    id INTEGER PRIMARY KEY AUTO_INCREMENT
                    , title VARCHAR(100), content VARCHAR(100))'''

        cursor.execute(sql) #sql 실행

        conn.commit() # 저장


except pymysql.InternalError as e:
        
    print(e)
finally:
    if conn:
        conn.close() # try 내의 전역변수

(1050, "Table 'mysql' already exists")

In [3]:
import pymysql


conn = pymysql.connect(
host ='localhost', user='root', password=비밀번호,
db='python', charset='utf8') #데이터베이스 접속

cursor = conn.cursor() #Cursor 객체 생성

sql = '''INSERT INTO mysql (id, title, content)
        VALUES (NULL, %s, %s)'''
           

cursor.execute(sql,('제목A','내용Z')) #sql 실행

conn.commit() 


cursor.close()
conn.close() # try 내의 전역변수

In [9]:
import pymysql


conn = pymysql.connect(
host ='localhost', user='root', password=비밀번호,
db='python', charset='utf8') #데이터베이스 접속

cursor = conn.cursor() #Cursor 객체 생성

sql = '''UPDATE mysql SET title = %s
            WHERE id = %s'''
           

cursor.execute(sql,('제목수정됨',1)) #sql 실행

conn.commit() 


cursor.close()
conn.close() # try 내의 전역변수

In [8]:
import pymysql


conn = pymysql.connect(
host ='localhost', user='root', password=비밀번호,
db='python', charset='utf8') #데이터베이스 접속

cursor = conn.cursor() #Cursor 객체 생성

sql = '''DELETE FROM MYSQL
            WHERE id = %s'''
           

cursor.execute(sql,(2)) #sql 실행

conn.commit() 


cursor.close()
conn.close() # try 내의 전역변수

In [16]:
import pymysql


conn = pymysql.connect(
host ='localhost', user='root', password=비밀번호,
db='python', charset='utf8') #데이터베이스 접속

cursor = conn.cursor() #Cursor 객체 생성

sql = '''SELECT * FROM MYSQL'''
           

cursor.execute(sql) #sql 실행
result = cursor.fetchall() #fetchall() 모두 조회 
print(result)
print(result[0])
print(result[0][1])


conn.commit() 


cursor.close()
conn.close() # try 내의 전역변수

((1, '제목수정됨', '내용Z'),)
(1, '제목수정됨', '내용Z')
제목수정됨

fetchall():모두조회

fetchmany() : 여러개 데이터 조회

fetchone: 하나만 조회

In [17]:
# member 테이블 만들기


import pymysql


conn = pymysql.connect(
host ='localhost', user='root', password=비밀번호,
db='python', charset='utf8') #데이터베이스 접속

cursor = conn.cursor() #Cursor 객체 생성

sql = '''CREATE TABLE member (
                    NUM INTEGER PRIMARY KEY AUTO_INCREMENT
                    , NAME VARCHAR(30), EMAIL VARCHAR(30), C_DATE DATETIME)'''

           

cursor.execute(sql) #sql 실행

conn.commit() 


cursor.close()
conn.close() # try 내의 전역변수

In [19]:
#  article  테이블 만들기


import pymysql


conn = pymysql.connect(
host ='localhost', user='root', password=비밀번호,
db='python', charset='utf8') #데이터베이스 접속

cursor = conn.cursor() #Cursor 객체 생성

sql = '''CREATE TABLE article (
                    ID INTEGER PRIMARY KEY AUTO_INCREMENT
                    , TITLE VARCHAR(30), CONTENT VARCHAR(30), WRITER VARCHAR(30),
                    HIT INTEGER, C_DATE DATETIME)'''

           

cursor.execute(sql) #sql 실행

conn.commit() 


cursor.close()
conn.close() # try 내의 전역변수

In [17]:
#  article  insert


import pymysql


conn = pymysql.connect(
host ='localhost', user='root', password='1234',
db='python', charset='utf8') #데이터베이스 접속

cursor = conn.cursor() #Cursor 객체 생성

sql = '''INSERT INTO article (
                    ID, TITLE, CONTENT, WRITER,
                    HIT, C_DATE)
        VALUES (NULL, %s, %s, %s, 0,now())'''

           

cursor.execute(sql,('제목','내용','파이썬')) #sql 실행

conn.commit() 


cursor.close()
conn.close() # try 내의 전역변수

In [30]:
#  article  insert


import pymysql


conn = pymysql.connect(
host ='localhost', user='root', password='1234',
db='python', charset='utf8') #데이터베이스 접속

cursor = conn.cursor() #Cursor 객체 생성

# sql = '''UPDATE ARTICLE SET
#         TITLE = %s, CONTENT = %s, HIT = %s
#         WHERE ID - %s'''

# 데이터 100개 입력
sql = '''INSERT INTO ARTICLE
 (ID, TITLE, CONTENT, WRITER, HIT, C_DATE)
 VALUES (NULL, %s, %s, %s, 0, NOW())'''
for i in range(1, 101):
    cursor.execute(sql, ('제목' + str(i), '내용' + str(i), '파이썬'))           

#cursor.execute(sql,('제목수정','내용수정',100, 1)) #sql 실행

conn.commit() 


cursor.close()
conn.close() # try 내의 전역변수

In [31]:
import pymysql

page_num = input('원하는 페이지 번호를 입력해주세요.')
#print(type(page_num)) # str 문자열 타입임.
page_num = int(page_num)
end_num = page_num *10
start_num = end_num - 9


conn = pymysql.connect(
host ='localhost', user='root', password='1234',
db='python', charset='utf8') #데이터베이스 접속

cursor = conn.cursor(pymysql.cursors.DictCursor) #Cursor 객체 생성

sql = '''SELECT *
            FROM article
            LIMIT %s, 5'''

cursor.execute(sql,(start_num-1)) #sql 실행

result = cursor.fetchall() #fetchall() 모두 조회 

print(len(result))


for row in result:
    print(row['ID'], row['TITLE'], row['CONTENT'], row['WRITER'],row['HIT'],row['C_DATE'])


conn.commit() 


cursor.close()
conn.close() # try 내의 전역변수

원하는 페이지 번호를 입력해주세요.1
5
1 제목 내용 파이썬 0 2020-01-28 10:35:39
2 제목1 내용1 파이썬 0 2020-01-28 11:25:53
3 제목2 내용2 파이썬 0 2020-01-28 11:25:53
4 제목3 내용3 파이썬 0 2020-01-28 11:25:53
5 제목4 내용4 파이썬 0 2020-01-28 11:25:53

In [36]:
#  MEMBER INSERT


import pymysql


conn = pymysql.connect(
host ='localhost', user='root', password='1234',
db='python', charset='utf8') #데이터베이스 접속

cursor = conn.cursor() #Cursor 객체 생성

# sql = '''INSERT INTO member (NUM, NAME, EMAIL, C_DATE)
#         VALUES (NULL, %s, %s, now())'''



sql = '''INSERT INTO MEMBER
         (NUM, NAME, EMAIL, C_DATE)
         VALUES (NULL, %s, %s, NOW())'''
for i in range(1, 101):
    cursor.execute(sql, ('제목' + str(i), 'a@a.com'))
           

#cursor.execute(sql,('a','a@a.com'))#sql 실행 #sql 실행


conn.commit() 


cursor.close()
conn.close() # try 내의 전역변수

In [29]:
import pymysql

page_num = input('원하는 페이지 번호를 입력해주세요.')
#print(type(page_num)) # str 문자열 타입임.
page_num = int(page_num)
end_num = page_num *10
start_num = end_num - 9


conn = pymysql.connect(
host ='localhost', user='root', password='1234',
db='python', charset='utf8') #데이터베이스 접속

cursor = conn.cursor(pymysql.cursors.DictCursor) #Cursor 객체 생성

sql = '''SELECT *
            FROM MEMBER
            LIMIT %s, 5'''

cursor.execute(sql,(start_num-1)) #sql 실행

result = cursor.fetchall() #fetchall() 모두 조회 

print(len(result))


for row in result:
    print(row['NUM'], row['NAME'], row['EMAIL'], row['C_DATE'])


conn.commit() 


cursor.close()
conn.close() # try 내의 전역변수

원하는 페이지 번호를 입력해주세요.1
5
2 제목1 a@a.com 2020-01-28 11:16:56
3 제목2 a@a.com 2020-01-28 11:16:56
4 제목3 a@a.com 2020-01-28 11:16:56
5 제목4 a@a.com 2020-01-28 11:16:56
6 제목5 a@a.com 2020-01-28 11:16:56

In [19]:
#  MEMBER update


import pymysql


conn = pymysql.connect(
host ='localhost', user='root', password='1234',
db='python', charset='utf8') #데이터베이스 접속

cursor = conn.cursor() #Cursor 객체 생성

sql = '''UPDATE MEMBER SET
        NAME = %s , EMAIL = %s
        WHERE NUM = %s'''

           

cursor.execute(sql,('aa','aa@aa.com',1))#sql 실행 #sql 실행

conn.commit() 


cursor.close()
conn.close() # try 내의 전역변수

In [22]:
#  MEMBER delete


import pymysql


conn = pymysql.connect(
host ='localhost', user='root', password='1234',
db='python', charset='utf8') #데이터베이스 접속

cursor = conn.cursor() #Cursor 객체 생성

sql = '''DELETE FROM MEMBER 
        
        WHERE NUM = 1'''

           

cursor.execute(sql)#sql 실행 #sql 실행

conn.commit() 


cursor.close()
conn.close() # try 내의 전역변수

In [7]:
import pymysql


conn = pymysql.connect(
host ='localhost', user='root', password='1234',
db='mydb', charset='utf8') #데이터베이스 접속

cursor = conn.cursor(pymysql.cursors.DictCursor) #Cursor 객체 생성

sql = '''SELECT id, year, area1, count(*) as cnt
            FROM accident
            GROUP BY AREA1, YEAR'''

cursor.execute(sql) #sql 실행

result = cursor.fetchall() #fetchall() 모두 조회 
for row in result:
    print(row['area1'], row['year'], row['cnt'])


conn.commit() 


cursor.close()
conn.close() # try 내의 전역변수

강원 2016 206
경기 2016 749
경남 2016 359
경북 2016 477
광주 2016 85
대구 2016 150
대전 2016 94
부산 2016 153
서울 2016 342
세종 2016 25
울산 2016 70
인천 2016 137
전남 2016 327
전북 2016 275
제주 2016 77
충남 2016 372
충북 2016 221

In [24]:
import pymysql


conn = pymysql.connect(
host ='localhost', user='root', password='1234',
db='mydb', charset='utf8') #데이터베이스 접속

cursor = conn.cursor(pymysql.cursors.DictCursor) #Cursor 객체 생성

sql = '''SELECT *
            FROM EMP'''

cursor.execute(sql) #sql 실행

result = cursor.fetchall() #fetchall() 모두 조회 

print(len(result))
for row in result:
    print(row['EMPNO'], row['ENAME'])


conn.commit() 


cursor.close()
conn.close() # try 내의 전역변수

14
7369 SMITH
7499 ALLEN
7521 WARD
7566 JONES
7654 MARTIN
7698 BLAKE
7782 CLARK
7788 SCOTT
7839 KING
7844 TURNER
7876 ADAMS
7900 JAMES
7902 FORD
7934 MILLER

In [5]:
import pymysql

page_num = input('원하는 페이지 번호를 입력해주세요.')
#print(type(page_num)) # str 문자열 타입임.
page_num = int(page_num)
end_num = page_num *10
start_num = end_num - 9


conn = pymysql.connect(
host ='localhost', user='root', password='1234',
db='mydb', charset='utf8') #데이터베이스 접속

cursor = conn.cursor(pymysql.cursors.DictCursor) #Cursor 객체 생성

sql = '''SELECT *
            FROM EMP
            LIMIT %s, 10'''

cursor.execute(sql,(start_num-1)) #sql 실행

result = cursor.fetchall() #fetchall() 모두 조회 

print(len(result))
for row in result:
    print(row['EMPNO'], row['ENAME'])


conn.commit() 


cursor.close()
conn.close() # try 내의 전역변수

원하는 페이지 번호를 입력해주세요.1
10
7369 SMITH
7499 ALLEN
7521 WARD
7566 JONES
7654 MARTIN
7698 BLAKE
7782 CLARK
7788 SCOTT
7839 KING
7844 TURNER

In [49]:
import pymysql
import re 



conn = pymysql.connect(
host ='localhost', user='root', password='1234',
db='mydb', charset='utf8') #데이터베이스 접속

cursor = conn.cursor(pymysql.cursors.DictCursor) #Cursor 객체 생성

sql = '''SELECT *
            FROM INFO
            '''

cursor.execute(sql) #sql 실행

result = cursor.fetchall() #fetchall() 모두 조회 

print(len(result))
for row in result:
    #print(row['ID'], row['NAME'], row['PERSON_NUMBER'])
    a = row['ID']
    b = row['NAME']
    c = row['PERSON_NUMBER']
    text = c 
    patturn = re.compile('(\d{6})-\d{7}')
    change = '\g<1>-*******'
    res = patturn.sub(change,text)
    print(a,b,res)


conn.commit() 


cursor.close()
conn.close() # try 내의 전역변수

7
a 일길동 751111-*******
b 이길동 761111-*******
c 삼길동 771111-*******
d 사길동 781111-*******
e 오길동 791111-*******
f 육길동 801111-*******
g 칠길동 811111-*******